name: crypto_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  intl: ^0.19.0
  # State Management
  flutter_bloc: ^9.0.0
  # Navigation
  go_router: ^14.1.0
  # Dependency Injection
  get_it: ^7.7.0
  # Networking
  dio: ^5.4.0
  # Secure Storage
  flutter_secure_storage: ^9.2.1
  # Persistent Storage
  shared_preferences: ^2.3.2
  # Biometric Authentication
  local_auth: ^2.2.0
  # Device Info
  device_info_plus: ^10.1.0
  # Root Check
  root_check_flutter: ^1.0.5
  # Firebase (Auth)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.9
  # UUID Generation
  uuid: ^4.4.0
  # SVG Support
  flutter_svg: ^2.0.10
  # Environment Variables
  flutter_dotenv: ^5.2.1
  # Image Caching
  cached_network_image: ^3.2.3
  # URL Launcher
  url_launcher: ^6.3.1
  # Send Email
  mailer: ^6.0.1
  # Cryptography
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - .env

